Change of pylint

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,12 @@ jobs:
 
     - name: Lint with pylint
       run: |
-        PYTHONIOENCODING=utf-8 pylint app/ src/ tests/ --fail-under=8 --output-format=colorized
+        SCORE=$(pylint app/ src/ tests/ --exit-zero | grep -oP 'rated at \K[0-9]+\.[0-9]+')
+        echo "Pylint score: $SCORE"
+        if (( $(echo "$SCORE < 8" | bc -l) )); then
+          echo "Pylint score is less than 8. Failing the workflow."
+          exit 1
+        fi
 
     - name: Test with pytest
       run: |
